version: '3.8'

services:
  airflow-webserver:
    build: .
    command: airflow webserver
    ports:
      - 8081:8080
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://streaming_user:streaming_pass@postgres:5432/streaming_db
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres

  airflow-scheduler:
    build: .
    command: airflow scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://streaming_user:streaming_pass@postgres:5432/streaming_db
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: streaming_db
      POSTGRES_USER: streaming_user
      POSTGRES_PASSWORD: streaming_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

